#!/usr/bin/env bash

if [[ ${1:+1} ]]; then 
    numbers=${1/"d"/" "}
    numberofdie=$(echo $numbers | awk '{print $1}')
    diespots=$(echo $numbers | awk '{print $2}')
    #printf "%s \n%s \n" $numberofdie $diespots
    
    printf "Rolling %sd%s" $numberofdie $diespots
    sleep 0.3
    printf "."
    sleep 0.3
    printf "."
    sleep 0.3
    printf ".\n"
    sleep 0.3

    for ((i=1;i<=numberofdie;i++));
    do
        output=$(( RANDOM % $diespots + 1))
        printf "%s " $output
    done
    echo ""
else
    printf "Rolling 1d6"
    sleep 0.3
    printf "."
    sleep 0.3
    printf "."
    sleep 0.3
    printf ".\n"
    sleep 0.3

    output=$(( RANDOM % 6 + 1 ))
    echo "$output"
fi