#!/usr/bin/env bash

drumroll () {

    if [[ ${1:+1} ]]; then
        announcement=$1
    else   
        announcement="Drumroll!"
    fi

    printf "%s\n" "$announcement"
    sleep 0.4
    echo "."
    sleep 0.4
    echo "."
    sleep 0.4
    echo "."
    sleep 0.4
}

if [[ ${1:+1} ]]; then 
    numbers=${1/"d"/" "}
    numberofdie=$(echo $numbers | awk '{print $1}')
    diespots=$(echo $numbers | awk '{print $2}')
    #printf "%s \n%s \n" $numberofdie $diespots
    
    heading=$(printf "Rolling %sd%s" $numberofdie $diespots)
    drumroll "$heading"

    for ((i=1;i<=numberofdie;i++));
    do
        output=$(( RANDOM % $diespots + 1))
        printf "%s " $output
    done
    echo ""
else
    drumroll "Rolling 1d6"

    output=$(( RANDOM % 6 + 1 ))
    echo "$output"
fi