#!/usr/bin/env bash

drumroll () {

    if [[ $# -gt 0 ]]; then
        announcement=$1
    else   
        announcement="Drumroll!"
    fi

    printf "%s\n" "$announcement"
    sleep 0.4
    echo "."
    sleep 0.4
    echo "."
    sleep 0.4
    echo "."
    sleep 0.4
}

# optstring="n"
# quickmode=1

# while getopts ${optstring} option; do
#     case ${option} in
#         n) quickmode=0;;
#     esac
# done

declare -l first=$1

if [[ $# -gt 0 && $first = "bart" ]]; then
    echo "THE, BART, THE"
elif [[ $# -gt 0 && $1 =~ [0-9]d[0-9] ]]; then 
    numbers=${1/"d"/" "}
    numberofdie=$(echo $numbers | awk '{print $1}')
    diespots=$(echo $numbers | awk '{print $2}')
    #printf "%s \n%s \n" $numberofdie $diespots
    
    heading=$(printf "Rolling %sd%s" $numberofdie $diespots)
    
    drumroll "$heading"

    for ((i=1;i<=numberofdie;i++));
    do
        output=$(( RANDOM % $diespots + 1))
        printf "%s " $output
    done
    echo ""
else
    drumroll "Rolling 1d6"

    output=$(( RANDOM % 6 + 1 ))
    echo "$output"
fi